### ISSUE TITLE
[Set up Transfer Rule Grammatical Categories] populate attributes from inflection features and classes

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#229]
In addition to filling out the a_gram_cat attribute, this tool could fill out other attributes. By looking at the target and source FLEx projects, specifically the the inflection features and classes, the tool could populate these attributes automatically.

**Comment by rmlockwood** [comment]
Also, consider filling out categories in the rule file based on the source FLEx project categories.

**Comment by bbryson** [comment]
I agree with the idea of filling in Attributes based on what is in the project.  This is better than "start with some common ones", because there is going to be a lot of variation across projects, and I think that would be confusing.  If it is already an Inflection Feature in FLEx, they probably do need to use it in rules.  Never mind that they might need to make up more; at least start with the Inflection Features that are in the FLEx project.

It would be really nice to have the Categories section populated based on the Categories in FLEx.  In terms of whether to use only adj (for instance) or also adj.*,  a rudimentary way to make a guess is to check if that category has any templates.  Only include adj.* for categories with templates.

**Comment by bbryson** [comment]
Issue #339 is specifically about slots in templates.  Created that one separately, so this issue can be specifically about Inflection Features and Inflection Classes.
