### ISSUE TITLE
[Sense Linker] Handle Sense Reordering Gracefully

### ISSUE THREAD

**Issue by MattGyverLee** [rmlockwood/FLExTrans#326]
I haven't tested the fragility of sense linking, but I see some hypothetical challenges. Please let me know If I'm oversimplifying or misunderstanding this.

Sense addition and reordering are a reality of lexicography, and it's not ideal for FLExTrans to limit this. With my current understanding of Sense Linking, reordering senses is dangerous as the sense nember is hard coded with the entry guid. 

I don't see an easy way to avaid this problem and still allow user editing, since entry hyperlinks don't seem to be specific to the sense guid. (After scanning this (https://github.com/sillsdev/FieldWorks/blob/4d8f17146bb8b1682f8ef80aa639e1b79789fe34/Src/xWorks/LinkListener.cs), I suspect that FLEx can handle a hard link to Sense rather than Entry, but it can't generate them from the UI.) Nevertheless, FLExTrans could warn the user when this might have happened.

This morning, I just watched a team rearranging a dozen senses into 4 homographs. Reordering or deleting senses could result in a link to the wrong sense, and the user may never know. Moving a sense between entries could be even more dangerous.

A greenlight idea is this: In Paratext, backtranslations are approved by verse ✅.  When the text changes, the translations are marked with ❓for review. Something similar could work here.

The Sense Linker could store the GUID of the target sense, and flag a sense link for review if:

- ❗Worst: The stored sense GUID doesn't match the current target Entry GUID+SenseNum. 
  - This should trigger a required review, allowing the user to choose:
      - The previously linked Sense by GUID (and update the Entry GUID+SenseNum).
      - The current target of Entry GUID+SenseNum (and update the stored Sense GGUID)
      - A different entry, and update both.

- ❓The target gloss is changed (not counting spacing).
  - If implemented, this should be an optional review so that it is not annoying.

**Comment by rmlockwood** [comment]
The fix I employed is to use links that have sense guids. This way if a user rearranges senses the guid link is unaffected. Also, if the user makes the sense into its own entry or merges two entries, the guid link will be unaffected. 
So now there is no need for a custom field to track which sense number of an entry is being linked to. For backward compatibility, this method will still be supported for existing entries. New links, though, will always be created with sense guids.
Now, if a user does a manual 'copy location as link' and pastes it in to the 'target equivalent' custom field, FLExTrans will still handle this, but it will assume sense 1 (if there is no custom field with sense number). So, in a new project, where there won't be a sense number custom field, it won't be possible to manually link to a 2nd sense or beyond. That will have to be done in the Sense Linker tool.
As for the flagging mentioned above, the user will continue to get a warning if a link doesn't match an existing sense.
Target gloss changes are irrelevant since glosses are not used when linking senses.
This solution does not help the situation where a specific entry and sense are referenced in the transfer rules file in the format xyz1.2, but a sense is rearranged somehow.

**Comment by MattGyverLee** [comment]
I'm glad to read that you're linking by GUID, that will be much more stable, as long as it doesn't affect your UI too negatively. 
 
>  This solution does not help the situation where a specific entry and sense are referenced in the transfer rules file in the format xyz1.2, but a sense is rearranged somehow.

Wouldn't this be a one-time (or just-in-time) upgrade to convert that format to a sense GUID? Or will the user still be adding those manually?
