### ISSUE TITLE
[Build Bilingual Lexicon] warning for words that have the same category and differ only in case.

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#515]
FLEx will allow you to have two words that differ only in case. They will be different headwords. E.g. book and booK. In the bilingual lexicon they will be book1.1 and booK1.1, but Apertium will match both of these. In other words it ignores case and will put out something like buch1.1/buch1.1. So it's probably good to give a warning when we find such words in the FLEx lexicon.

**Comment by bbryson** [comment]
What about the case where we truly want two words that differ only in case, such as "the word" versus "the Word".  Is there a way to preserve that difference in FLExTrans?

If we have a proper noun and a noun that are the same except for case, will the case of the proper noun be preserved in the output because they have different Parts of Speech?

**Comment by rmlockwood** [comment]
When two words are different parts of speech we won't have an issue. So one can be upper and one lower case, for example.

**Comment by rmlockwood** [comment]
Fixed in PR #520
