### ISSUE TITLE
[Rule Assistant] Bantu agreement not working with T-M pair

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#651]
I wasn't right when I said it was working.

See the FLEx backup projects that are here: https://drive.google.com/drive/folders/1_5jblrMEF1YKMMsjgnbmo08YKnBITxNv

Two problems so far:

1. The noun rule only checks the 1\~2 class and always outputs 1\~2 for the prefix.
2. In the UI I can't select number as the set of features to match on the adjective. I think this is because there is no ValidFeatures section in the GUI xml for adj.
[RuleAssistantRules.txt](https://github.com/user-attachments/files/15566772/RuleAssistantRules.txt)

**Comment by mr-martian** [comment]
The Meetto project listed `number` under `Inflectable Features`, but the code was only checking `Affix Templates`. It is now checking both.

**Comment by rmlockwood** [comment]
Problem #2 is now fixed (build 61), But the rules are still not coming out right. The macro m_n_affix_from_n has only one when block checking for gender value 1~2. It should have blocks for 3~4, 5~6 and 9~10. Similar thing for the macro m_adj_affix_from_n.

**Comment by mr-martian** [comment]
The problem is that we've been determining what stem tags are possible by retrieving a list of which tags actually occur on stems, and the Meetto project only has 3 nouns with noun class specified and they all happen to be class `1~2`.

So we would get a more correct-seeming rule if we used the list of all feature values defined in the project, but it wouldn't actually change the rule's output in any way.

I suppose I could have it generate from the longer list and issue a warning for features that aren't used. What do you think?

**Comment by rmlockwood** [comment]
I think we should go with the list of all features defined. I don't think there needs to be a warning, it won't hurt if we are checking for a feature value and it never occurs.

**Comment by rmlockwood** [comment]
Once the change is made to get all features defined instead of what is found on words, this issue can be closed. After assigning words the proper classes and testing, the transfer rules created by the backend produce the expected results for nouns and noun adjective pairs. See updated files. Very nice!

**Comment by rmlockwood** [comment]
Great that source project features are being checked, but the word ettengu still doesn't work because 7~8 is not in the list of possible suffixes for the attribute a_n_number_slot.

**Comment by mr-martian** [comment]
Ah yes, because attributes need to be the union of source and target.

**Comment by rmlockwood** [comment]
Working now for all my tests!
