### ISSUE TITLE
[Rule Assistant] Features shouldn't be bold on affixes

### ISSUE THREAD

**Issue by bbryson** [rmlockwood/FLExTrans#722]
On the target side, I wouldn't expect that any affixes should have their features displayed in bold.  These don't CONTRIBUTE features, do they?  Isn't it the case that they need to GET their features from somewhere, whether it is from a word in the target phrase or something on the source side?

![11-Suffixes bold features](https://github.com/user-attachments/assets/98dec69d-1768-48c5-9d01-961bee406702)

**Comment by mr-martian** [comment]
I don't know about the UI, but the backend uses the following as sources (in order):
1. anything in the source language
2. stem of target language head
3. affixes of target language head
4. any other target language stem
5. (non-head target affixes are never used)

**Comment by bbryson** [comment]
That sounds reasonable.  So this is largely about the UI then.

**Comment by rmlockwood** [comment]
I think we have used bold just to indicate features that are on the head. Bold=head.

**Comment by rmlockwood** [comment]
@bbryson Are you ok if we close this issue? Are you happy now that everything on the target head is bold? In the example below, it's appropriate, I think, that the suffix number feature on the head is bold because the adj number feature is going to agree with it.
![image](https://github.com/user-attachments/assets/71a59f0b-c280-47ff-bdf8-07f34e9a516c)
