### ISSUE TITLE
[Rule Assistant] UI Change to right-click

### ISSUE THREAD

**Issue by rmlockwood** [rmlockwood/FLExTrans#759]
We had a couple comments from the workshop that it would be more intuitive to right-click in the Rule Assistant to bring up context menus. If possible, let's switch to that.

**Comment by AndyBlack** [comment]
In version 0.26.1, made it so that either left- or right-click will bring up the choosers.
We removed right-click back in May because the context menu could show incorrectly.  By allowing either left- or right-click, we avoid that problem. See https://drive.google.com/file/d/1g5VMr9OAxog6RABVTyhnQuUqZMo5CNkA/view?usp=sharing

**Comment by rmlockwood** [comment]
verified in 0.27.0
